name: A workflow for my Hello World file
on: 
  push:
    branches:
    - test-branch
  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "test raghu"
